{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "51b1bb3a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import csv\n",
    "import json\n",
    "import joblib\n",
    "import numpy as np\n",
    "from typing import List, Dict, Tuple\n",
    "import pandas as pd\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer\n",
    "from sklearn.model_selection import train_test_split\n",
    "random_state =42\n",
    "\n",
    "vocab_size = 3000 \n",
    "\n",
    "RAW_CSV = \"data/raw/sms.csv\"              # file gốc: 2 cột \"label\",\"text\"\n",
    "TRAIN_OUT = \"data/processed/train.csv\"    # output train\n",
    "TEST_OUT  = \"data/processed/test.csv\"     # output test\n",
    "VEC_PKL   = \"artifacts/vectorizer.pkl\"    # pickle vectorizer cho Bước 3/4\n",
    "VOCAB_TXT = \"artifacts/vocab.txt\"         # vocab (tham khảo)\n",
    "TEST_SIZE = 0.2                           # 80/20 split\n",
    "\n",
    "# -----------------------------\n",
    "# 1) STOPWORDS & CLEANING\n",
    "# -----------------------------\n",
    "STOPWORDS = {\n",
    "    \"a\",\"an\",\"the\",\"is\",\"are\",\"am\",\"was\",\"were\",\"be\",\"been\",\"being\",\"i\",\"you\",\"he\",\"she\",\"it\",\"we\",\"they\",\"me\",\"him\",\"her\",\"us\",\"them\",\n",
    "    \"this\",\"that\",\"these\",\"those\",\"there\",\"here\",\"of\",\"to\",\"in\",\"on\",\"for\",\"from\",\"with\",\"by\",\"at\",\"as\",\"about\",\"into\",\"over\",\"after\",\n",
    "    \"before\",\"between\",\"and\",\"or\",\"but\",\"if\",\"then\",\"so\",\"because\",\"while\",\"than\",\"though\",\"although\",\"not\",\"no\",\"do\",\"does\",\"did\",\"doing\",\n",
    "    \"done\",\"dont\",\"didnt\",\"doesnt\",\"isnt\",\"arent\",\"wasnt\",\"werent\",\"cant\",\"cannot\",\"my\",\"your\",\"his\",\"her\",\"its\",\"our\",\"their\",\n",
    "    \"have\",\"has\",\"had\",\"having\",\"will\",\"would\",\"shall\",\"should\",\"can\",\"could\",\"may\",\"might\",\"must\",\n",
    "    \"im\",\"ive\",\"youre\",\"hes\",\"shes\",\"weve\",\"theyre\",\"ill\",\"youll\",\"dont\",\"cant\",\"wont\",\"didnt\",\"couldnt\",\"shouldnt\",\"wouldnt\",\"lets\"\n",
    "}\n",
    "\n",
    "def keep_letters_and_spaces(s: str) -> str:\n",
    "    \"\"\"\n",
    "    Chỉ giữ lại chữ cái (a-z) và khoảng trắng\n",
    "    \n",
    "    Tham số:\n",
    "        s: chuỗi đã lowercase\n",
    "        \n",
    "    Trả về:\n",
    "        Chuỗi chỉ chứa a-z và space\n",
    "        \n",
    "    Ví dụ:\n",
    "        \"hello123!@#world\" -> \"hello   world\"\n",
    "    \"\"\"\n",
    "    out = []\n",
    "    for ch in s:\n",
    "        if 'a' <= ch <= 'z' or ch == ' ':\n",
    "            out.append(ch)\n",
    "        else:\n",
    "            out.append(' ')\n",
    "    return ''.join(out)\n",
    "\n",
    "\n",
    "def clean_text(text: str, stopwords: set) -> str: #Làm sạch văn bản: lowercase -> loại ký tự đặc biệt -> loại stopword\n",
    "    \"\"\"\n",
    "        text: văn bản cần làm sạch\n",
    "        stopwords: tập hợp các từ dừng\n",
    "        \n",
    "    Trả về:\n",
    "        Văn bản đã làm sạch\n",
    "        \n",
    "    Các bước:\n",
    "        1. Chuyển về chữ thường\n",
    "        2. Loại bỏ ký tự đặc biệt, chỉ giữ a-z và space\n",
    "        3. Loại bỏ khoảng trắng thừa\n",
    "        4. Loại bỏ stopwords\n",
    "        5. Loại bỏ từ có độ dài <= 1\n",
    "    \"\"\"\n",
    "    text = text.lower()# Bước 1: lowercase\n",
    "    \n",
    "\n",
    "    text = keep_letters_and_spaces(text)# Bước 2: chỉ giữ chữ cái và space\n",
    "    \n",
    "    text = ' '.join(text.split()) # Bước 3: loại khoảng trắng thừa\n",
    "    \n",
    "    \n",
    "    words = text.split()\n",
    "    words = [w for w in words if w not in stopwords and len(w) > 1]# Bước 4 & 5: tách từ, loại stopwords và từ ngắn\n",
    "    \n",
    "    return ' '.join(words)\n",
    "\n",
    "\n",
    "# -----------------------------\n",
    "# *) ĐỌC VÀ LÀM SẠCH DỮ LIỆU\n",
    "# -----------------------------\n",
    "def load_and_clean_data(csv_path: str, stopwords: set) -> Tuple[List[str], List[int]]:\n",
    "    \"\"\"\n",
    "    Đọc file CSV và làm sạch dữ liệu\n",
    "    \n",
    "    Tham số:\n",
    "        csv_path: đường dẫn file CSV (cột 1: label, cột 2: text)\n",
    "        stopwords: tập stopwords\n",
    "        \n",
    "    Trả về:\n",
    "        (texts, labels) - danh sách văn bản đã làm sạch và nhãn (0=ham, 1=spam)\n",
    "    \"\"\"\n",
    "    print(f\"\\n📖 Đọc dữ liệu từ: {csv_path}\")\n",
    "    \n",
    "    texts = []\n",
    "    labels = []\n",
    "    \n",
    "    # Đọc file CSV\n",
    "    with open(csv_path, 'r', encoding='latin-1') as f:\n",
    "        reader = csv.reader(f)\n",
    "        header = next(reader)  # bỏ qua header\n",
    "        \n",
    "        for row in reader:\n",
    "            if len(row) < 2:\n",
    "                continue\n",
    "                \n",
    "            label_str = row[0].strip().lower()  # 'ham' hoặc 'spam'\n",
    "            raw_text = row[1].strip()\n",
    "            \n",
    "            \n",
    "            cleaned = clean_text(raw_text, stopwords) # Làm sạch văn bản\n",
    "            \n",
    "            \n",
    "            label_int = 1 if label_str == 'spam' else 0 # Chuyển label thành số: ham=0, spam=1\n",
    "            \n",
    "                             \n",
    "            if cleaned:# Chỉ giữ lại nếu văn bản không rỗng sau khi làm sạch\n",
    "                texts.append(cleaned)\n",
    "                labels.append(label_int)\n",
    "    \n",
    "    print(f\"✅ Đọc thành công {len(texts)} tin nhắn\")\n",
    "    print(f\"   - HAM (0): {labels.count(0)} tin\")\n",
    "    print(f\"   - SPAM (1): {labels.count(1)} tin\")\n",
    "    \n",
    "    return texts, labels\n",
    "\n",
    "\n",
    "# -----------------------------\n",
    "# 3) CHIA TRAIN/TEST\n",
    "# -----------------------------\n",
    "def split_train_test(texts: List[str], labels: List[int], \n",
    "                     test_size: float = 0.2, \n",
    "                     random_state: int = 42) -> Tuple:\n",
    "    \"\"\"\n",
    "    Chia dữ liệu thành tập train và test\n",
    "    \n",
    "    Tham số:\n",
    "        texts: danh sách văn bản\n",
    "        labels: danh sách nhãn\n",
    "        test_size: tỷ lệ test (0.2 = 20%)\n",
    "        random_state: seed cho random\n",
    "        \n",
    "    Trả về:\n",
    "        X_train, X_test, y_train, y_test\n",
    "    \"\"\"\n",
    "    print(f\"\\n Chia dữ liệu: {int((1-test_size)*100)}% train, {int(test_size*100)}% test\")\n",
    "    \n",
    "    X_train, X_test, y_train, y_test = train_test_split(\n",
    "        texts, labels, \n",
    "        test_size=test_size, \n",
    "        random_state=random_state,\n",
    "        stratify=labels  # đảm bảo tỷ lệ ham/spam đều trong train và test\n",
    "    )\n",
    "    \n",
    "    print(f\"✅ Train: {len(X_train)} mẫu\")\n",
    "    print(f\"✅ Test:  {len(X_test)} mẫu\")\n",
    "    \n",
    "    return X_train, X_test, y_train, y_test\n",
    "\n",
    "\n",
    "# -----------------------------\n",
    "# 4) VECTOR HÓA VĂN BẢN\n",
    "# -----------------------------\n",
    "def create_vectorizer(vocab_size: int = 3000, method: str = 'tfidf'):\n",
    "    \"\"\"\n",
    "    Tạo vectorizer để chuyển văn bản thành vector số\n",
    "    \n",
    "    Tham số:\n",
    "        vocab_size: số lượng từ trong vocabulary\n",
    "        method: 'tfidf' hoặc 'count'\n",
    "        \n",
    "    Trả về:\n",
    "        Vectorizer object\n",
    "        \n",
    "    Giải thích:\n",
    "        - TF-IDF: Term Frequency - Inverse Document Frequency\n",
    "          + Đo lường mức độ quan trọng của từ trong văn bản\n",
    "          + Từ xuất hiện nhiều trong 1 văn bản nhưng ít trong toàn bộ → quan trọng\n",
    "          \n",
    "        - Count: Đơn giản đếm số lần xuất hiện của từ\n",
    "    \"\"\"\n",
    "    print(f\"\\n🔢 Tạo vectorizer ({method.upper()}) với vocab_size={vocab_size}\")\n",
    "    \n",
    "    if method == 'tfidf':\n",
    "        vectorizer = TfidfVectorizer(\n",
    "            max_features=vocab_size,  # giới hạn số từ\n",
    "            ngram_range=(1, 2),       # unigram và bigram (từ đơn và cụm 2 từ)\n",
    "            min_df=2,                 # từ phải xuất hiện ít nhất 2 lần\n",
    "            max_df=0.95               # loại từ xuất hiện quá nhiều (>95% văn bản)\n",
    "        )\n",
    "    else:\n",
    "        vectorizer = CountVectorizer(\n",
    "            max_features=vocab_size,\n",
    "            ngram_range=(1, 2),\n",
    "            min_df=2,\n",
    "            max_df=0.95\n",
    "        )\n",
    "    \n",
    "    return vectorizer\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
